"use client";

import React from "react";
import { useQuery } from "@tanstack/react-query";
import { api } from "@/lib/api";
import { Download, FileText, Clock, CheckCircle } from "lucide-react";

export default function ExportsPage() {
  const { data: exports, isLoading } = useQuery({
    queryKey: ["exports"],
    queryFn: async () => {
      const res = await api.get("/exports");
      return res.data.data;
    },
  });

  const handleDownload = (exportId: string) => {
    const token = localStorage.getItem("morphe_token");
    const downloadUrl = `http://localhost:8000/api/v1/exports/${exportId}/download`;
    
    // Trigger file download
    fetch(downloadUrl, {
      headers: {
        Authorization: `Bearer ${token}`
      }
    })
      .then((res) => res.blob())
      .then((blob) => {
        const url = window.URL.createObjectURL(blob);
        const a = document.createElement("a");
        a.href = url;
        a.download = `export_${exportId.substring(0, 8)}`;
        document.body.appendChild(a);
        a.click();
        a.remove();
      })
      .catch((err) => alert("Failed to download artifact: " + err.message));
  };

  return (
    <div className="space-y-6 max-w-7xl mx-auto">
      <div>
        <h1 className="text-2xl font-bold text-slate-900 tracking-tight">Generated Artifact Exports</h1>
        <p className="text-sm text-slate-500 mt-1">
          Download history of all publisher-styled PDF, DOCX, LaTeX, and HTML documents generated by MORPHE.
        </p>
      </div>

      <div className="bg-white rounded-xl border border-slate-200 shadow-sm overflow-hidden">
        <div className="px-6 py-4 border-b border-slate-200 bg-slate-50/50 flex items-center justify-between">
          <h3 className="font-bold text-slate-800 text-sm">Export Artifact History</h3>
          <span className="text-xs font-semibold text-slate-500">{exports?.length ?? 0} Artifacts</span>
        </div>

        {isLoading ? (
          <div className="p-8 text-center text-slate-400 text-sm">Loading exports...</div>
        ) : !exports || exports.length === 0 ? (
          <div className="p-12 text-center">
            <Download className="h-10 w-10 text-slate-300 mx-auto mb-2" />
            <p className="font-semibold text-slate-700 text-sm">No Export Artifacts Generated Yet</p>
            <p className="text-xs text-slate-400 mt-1">Go to a document workspace and select "Generate & Export" to build output files.</p>
          </div>
        ) : (
          <div className="divide-y divide-slate-100">
            {exports.map((art: any) => (
              <div key={art.id} className="p-5 hover:bg-slate-50/80 transition-colors flex items-center justify-between">
                <div className="flex items-center gap-4">
                  <div className="h-10 w-10 rounded-xl bg-blue-50 text-blue-600 font-extrabold text-xs flex items-center justify-center uppercase shrink-0">
                    {art.format}
                  </div>
                  <div>
                    <div className="flex items-center gap-2">
                      <h4 className="font-bold text-slate-900 text-sm">{art.format} Document</h4>
                      <span className="text-[10px] font-bold px-2 py-0.5 rounded bg-blue-100 text-blue-700">
                        {art.publisher_code || "IEEE"} Format
                      </span>
                    </div>
                    <p className="text-xs text-slate-500 mt-0.5">
                      Created: {new Date(art.created_at).toLocaleString()} | Size: {Math.round(art.file_size / 1024)} KB
                    </p>
                  </div>
                </div>

                <button
                  onClick={() => handleDownload(art.id)}
                  className="px-4 py-2 rounded-xl bg-blue-600 hover:bg-blue-500 text-white font-semibold text-xs flex items-center gap-2 shadow-sm transition-all"
                >
                  <Download className="h-4 w-4" /> Download File
                </button>
              </div>
            ))}
          </div>
        )}
      </div>
    </div>
  );
}
